export enum ManagementBusinessKeys {
  ID = "businessId",
  NAME = "businessName",
  DESCRIPTION = "businessDes",
  SIZE = "businessSize",
  NATIONALITY = "nationality",
  SLOGAN = "businessSlogan",
  BENEFITS = "benefit",
  IMAGE = "image",
  INDUSTRY = "industryDes",
  ADDRESS = "address",
  STREET = "street",
  WARD = "ward",
  DISTRICT = "district",
  CITY = "city",
  WEBSITE = "website",
  CONTACT = "contact",
  CREATED_AT = "createdDate",
  MODIFIED_AT = "modifiedDate",
  CREATED_BY = "createdBy",
  MODIFIED_BY = "modifiedBy",
  ACTIONS = "actions",
}
