export enum QueryKey {
  // Management
  GET_USERS = "GET_USERS",
  GET_USER_DETAIL = "GET_USER_DETAIL",

  GET_BLOGS = "GET_BLOGS",
  GET_BLOG_DETAIL = "GET_BLOG_DETAIL",

  GET_BUSINESSES = "GET_BUSINESSES",
  GET_BUSINESS_DETAIL = "GET_BUSINESS_DETAIL",

  GET_JOBS = "GET_JOBS",
  GET_JOB_DETAIL = "GET_JOB_DETAIL",

  // User
  GET_USER_PROFILE = "GET_USER_PROFILE",
  GET_BLOGS_USER = "GET_BLOG_USER",
  GET_BLOG_USER_DETAIL = "GET_BLOG_USER_DETAIL",
  GET_BUSINESSES_USER = "GET_BUSINESS_USER",
  GET_BUSINESS_USER_DETAIL = "GET_BUSINESS_USER_DETAIL",
  GET_JOBS_USER = "GET_JOB_USER",
  GET_JOBS_USER_DETAIL = "GET_JOB_USER_DETAIL",

  // Business
  GET_BUSINESSES_BUSINESS = "GET_BUSINESS_BUSINESS",
}
