export enum QueryKey {
  GET_USERS = "GET_USERS",
  GET_USER_DETAIL = "GET_USER_DETAIL",

  GET_BLOGS = "GET_BLOGS",
  GET_BLOG_DETAIL = "GET_BLOG_DETAIL",

  GET_BUSINESSES = "GET_BUSINESSES",
  GET_BUSINESS_DETAIL = "GET_BUSINESS_DETAIL",

  GET_JOBS = "GET_JOBS",
  GET_JOB_DETAIL = "GET_JOB_DETAIL",
}
